# Generated by Django 4.2.13 on 2025-03-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susaf_susoft', '0003_sprint_task_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
